# Generated by Django 3.2.6 on 2021-08-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudesReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('number_of_persons', models.IntegerField(blank=True)),
                ('reservation_date', models.DateTimeField(db_index=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reservation_date'],
            },
        ),
    ]
