# Generated by Django 3.2.7 on 2021-09-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('available', models.BooleanField()),
                ('category', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Plato Fuerte', 'Plato Fuerte'), ('Postre', 'Postre'), ('Bebidas', 'Bebidas')], default='Plato Fuerte', max_length=75)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
