# Generated by Django 3.2.6 on 2021-08-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_disponibilidad_horario_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='status',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
