# Generated by Django 3.2.7 on 2021-09-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesreserva',
            name='status',
            field=models.CharField(choices=[('Asistió', 'Asistió'), ('Faltó', 'Faltó'), ('Cancelado', 'Cancelado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50),
        ),
    ]
