# Generated by Django 3.2.7 on 2021-09-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_solicitudesreserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.CharField(default='', max_length=500),
        ),
    ]
