# Generated by Django 3.2.6 on 2021-08-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_disponibilidad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='num_chairs',
            field=models.IntegerField(),
        ),
    ]
