# Generated by Django 3.2.7 on 2021-09-08 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_mesa_num_chairs'),
        ('management', '0004_menu_imagen'),
    ]

    operations = [
    ]
